set(CMAKE_EXECUTABLE_SUFFIX ".lno")
set(CMAKE_EXECUTABLE_SUFFIX_C ".lno")
set(CMAKE_EXECUTABLE_SUFFIX_ASM ".lno")
set(CMAKE_C_OUTPUT_EXTENSION ".obj")
set(CMAKE_ASM_OUTPUT_EXTENSION ".obj")
set(CMAKE_ASM_SOURCE_FILE_EXTENSIONS asm;src)

set(CMAKE_C_FLAGS_DEBUG_INIT "-g -O0")
set(CMAKE_C_FLAGS_RELEASE_INIT "-O3")
set(CMAKE_C_FLAGS_MINSIZEREL_INIT "-O2")
set(CMAKE_C_FLAGS_RELWITHDEBINFO_INIT "-g -O3")
set(CMAKE_ASM_FLAGS_DEBUG_INIT "-g")
set(CMAKE_ASM_FLAGS_RELEASE_INIT "")
set(CMAKE_ASM_FLAGS_MINSIZEREL_INIT "")
set(CMAKE_ASM_FLAGS_RELWITHDEBINFO_INIT "-g")

set(CMAKE_C_COMPILE_OBJECT
	"<CMAKE_C_COMPILER> -Ml <DEFINES> <INCLUDES> <FLAGS> -c -o <OBJECT> <SOURCE>")
set(CMAKE_ASM_COMPILE_OBJECT
	"<CMAKE_ASM_COMPILER> -Ml <DEFINES> <INCLUDES> <FLAGS> -c -o <OBJECT> <SOURCE>")
set(CMAKE_C_LINK_EXECUTABLE
	"<CMAKE_C_COMPILER> -Ml <FLAGS> <CMAKE_C_LINK_FLAGS> <LINK_FLAGS> -tmp -o <TARGET> <OBJECTS> <LINK_LIBRARIES>")
set(CMAKE_ASM_LINK_EXECUTABLE
	"<CMAKE_ASM_COMPILER> -Ml <FLAGS> <CMAKE_ASM_LINK_FLAGS> <LINK_FLAGS> -tmp -o <TARGET> <OBJECTS> <LINK_LIBRARIES>")

set(CMAKE_C_DEPENDS_USE_COMPILER FALSE)
set(CMAKE_ASM_DEPENDS_USE_COMPILER FALSE)
